platform :ios , '7.0'

pod 'AFNetworking', '~> 2.2'
pod 'Facebook-iOS-SDK', '~> 3.13'
pod 'pop', '~> 1.0'
pod 'EMAccordionTableViewController', '~> 0.4'
pod 'MONActivityIndicatorView', '~> 0.0.1'
pod 'ReactiveCocoa', '~> 2.3'
pod 'IQKeyboardManager'
pod 'THCalendarDatePicker', '~> 0.1.1'